### ISSUE TITLE
What is 'files_allowed' method?

### ISSUE THREAD

**Issue by jkeenan** [rjbs/CPAN-Mini#11]
The documentation for the 'exact_mirror' option refers to a 'files_allowed' method.

http://search.cpan.org/grep?cpanid=RJBS&release=CPAN-Mini-1.111016&string=files_allowed&i=1&n=1&C=0

However, I no such method exists.  Shouldn't this be 'file_allowed'?

Thank you very much.
Jim Keenan

**Comment by rjbs** [comment]
It should!  Fixed, thanks!
