### ISSUE TITLE
Using CPAN::Mini creates local mirror

### ISSUE THREAD

**Issue by YaoMingYa** [rjbs/CPAN-Mini#20]
minicpan -l /home/yaoming/mirror/cpan -r http://mirrors.163.com/cpan/
warning "
unable to contact the remote mirror at /usr/local/share/perl/5.2 6.1/CPAN/Mini/App.pm line 120.
"

**Comment by YaoMingYa** [comment]
the reason maybe  the limit of local ip , you can  set http_proxy like this "export http_proxy="http://xx.xx.xx.xx:port"" to attempt figure it out

**Comment by rjbs** [comment]
I'm really not sure I understand this issue, and am closing it.
